server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyshow
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secretKey=bookmyshowsecretkeymustbe32charslong1234567890

# Stripe (dummy for now - only payment API will fail, rest all works)
stripe.api.key=your_stripe_key_here
stripe.webhook.secret=whsec_dummy

# Frontend
frontend.url=http://localhost:3000

# Email DISABLED for now
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivamkumarnayak13@gmail.com
spring.mail.password=mqlg vnhz uhab jcqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false


# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10